import test from 'node:test';
import assert from 'node:assert/strict';
import {runAdminRequest,validateCampUpdate,londonToISO,isAdmin} from '../lib/admin-validation.mjs';
const owner='user_owner123';
const valid={title:'October camp',subtitle:'Physical literacy through basketball',tag:'CAMP',description:'Enjoy movement',arrival_information:'Bring water',location:'Venue TBC',start_local:'2026-10-26T10:00',end_local:'2026-10-28T15:00',min_age:8,max_age:18,price_gbp:'60.00',capacity:25,published:true,booking_open:true};
for(const [name,userId,adminId,status] of [['anonymous',null,owner,401],['another account','user_else',owner,403],['missing configuration',owner,undefined,403],['invalid configuration',owner,'owner123',403]]){
 test(`${name} cannot reach privileged operation`,async()=>{let called=false;const result=await runAdminRequest(new Request('https://example.com/api/admin/camps'),{authenticate:async()=>({userId}),adminId,operation:async()=>{called=true;}});assert.equal(result.status,status);assert.equal(called,false);assert.match(result.headers.get('cache-control'),/no-store/);});
}
test('only exact owner matches',()=>{assert.equal(isAdmin(owner,owner),true);assert.equal(isAdmin(owner,owner+'x'),false);});
test('owner can read data',async()=>{const response=await runAdminRequest(new Request('https://example.com/api/admin/camps'),{authenticate:async()=>({userId:owner}),adminId:owner,operation:async()=>({camps:[]})});assert.equal(response.status,200);assert.deepEqual(await response.json(),{camps:[]});});
for(const origin of [null,'https://attacker.example']) test(`write rejected for origin ${origin}`,async()=>{let called=false;const headers={'Content-Type':'application/json'};if(origin)headers.Origin=origin;const response=await runAdminRequest(new Request('https://example.com/api/admin/camps',{method:'PATCH',headers}),{authenticate:async()=>({userId:owner}),adminId:owner,operation:async()=>{called=true;}});assert.equal(response.status,403);assert.equal(called,false);});
test('owner same-origin JSON write succeeds',async()=>{const response=await runAdminRequest(new Request('https://example.com/api/admin/camps',{method:'PATCH',headers:{Origin:'https://example.com','Content-Type':'application/json'}}),{authenticate:async()=>({userId:owner}),adminId:owner,operation:async()=>({saved:true})});assert.equal(response.status,200);});
test('camp values convert GBP and UK times',()=>{const result=validateCampUpdate(valid);assert.equal(result.price_pence,6000);assert.equal(result.starts_at,'2026-10-26T10:00:00.000Z');assert.equal(londonToISO('2027-05-31T10:00'),'2027-05-31T09:00:00.000Z');assert.equal(londonToISO('2027-03-28T15:00'),'2027-03-28T14:00:00.000Z');});
for(const [name,changes] of [['unknown field',{user_id:owner}],['fractional capacity',{capacity:1.5}],['invalid price',{price_gbp:'-1'}],['invalid age',{max_age:7}],['reversed dates',{end_local:'2026-10-25T15:00'}],['hidden open camp',{published:false}],['invalid date',{start_local:'2026-02-30T10:00'}],['string boolean',{published:'true'}]])test(`rejects ${name}`,()=>assert.throws(()=>validateCampUpdate({...valid,...changes})));
test('rejects ambiguous and missing clock-change times',()=>{assert.throws(()=>londonToISO('2027-03-28T01:30'));assert.throws(()=>londonToISO('2026-10-25T01:30'));});
