import { ArrowUpRight, ArrowRight, MoveUpRight, Sparkles, Heart, Users, CircleCheck, Dribbble } from 'lucide-react';
import Camps from '@/components/camps';
import Account from '@/components/account';
export default function Home() {
 return <>
  <header className="header"><a href="#" className="brand" aria-label="Elevate Sports home"><span className="brand-mark">E</span><span>ELEVATE<small>SPORTS</small></span></a><nav aria-label="Main navigation"><a href="#approach">Our approach</a><a href="#camps">Basketball camps</a></nav><div className="header-actions"><Account/><a className="button button-small" href="#camps">Find a camp <ArrowUpRight size={17}/></a></div></header>
  <main>
   <section className="hero">
    <div className="hero-copy"><div className="eyebrow"><span/> BIG POSSIBILITIES. ONE BASKETBALL.</div><h1>A love of<br/>movement<br/>starts <em>here.</em><span className="headline-star" aria-hidden="true">✳</span></h1><p>More than learning the game.<br/>Building the confidence to join in, have a go<br className="desktop-break"/> and keep moving.</p><a href="#camps" className="button">Explore our camps <ArrowUpRight size={20}/></a><div className="hero-note"><span className="mini-ball"><Dribbble size={21}/></span> For the joy of playing. For life.</div></div>
    <div className="hero-visual"><div className="hero-image" role="img" aria-label="Young people playing basketball together on an outdoor court"/><div className="photo-shade"/><span className="photo-label">SMALL STEPS. BIG LEAPS.</span><div className="hero-sticker"><MoveUpRight size={30}/><span>More play.<br/>More possibility.</span></div><div className="photo-caption"><span>THE GAME IS JUST<br/>THE BEGINNING.</span><Dribbble size={47} strokeWidth={1.2}/></div></div>
   </section>
   <div className="values-strip" aria-label="Our values"><span>MOVE WITH CONFIDENCE</span><span aria-hidden="true">✳</span><span>PLAY WITH PURPOSE</span><span aria-hidden="true">✳</span><span>GROW TOGETHER</span><span aria-hidden="true">✳</span><span>ENJOY THE JOURNEY</span></div>
   <section id="approach" className="approach section-wrap"><div className="section-kicker">01 / THE ELEVATE APPROACH</div><div className="approach-grid"><h2>Basketball is our tool.<br/><span>A love of movement<br/>is our goal.</span></h2><div><p className="mission">At Elevate, physical literacy means helping young people build a positive, lasting relationship with movement — through sport and games they actually enjoy.</p><p className="secondary-copy">Every pass, every game and every new challenge is a chance to discover what they can do. We make space for young people to learn, connect and find their own way to move.</p></div></div><div className="principles"><article><span className="principle-icon peach"><Sparkles size={24}/></span><h3>Confidence to try</h3><p>Small wins that help young people feel capable, on and off the court.</p></article><article><span className="principle-icon green"><Users size={24}/></span><h3>A place to belong</h3><p>Shared games, new connections and the simple joy of being part of a team.</p></article><article><span className="principle-icon yellow"><Heart size={24}/></span><h3>Movement that lasts</h3><p>Positive experiences today. A reason to keep coming back tomorrow.</p></article></div></section>
   <section id="camps" className="camps-section section-wrap"><div className="section-kicker">02 / GET ON THE COURT</div><div className="section-heading"><div><h2>Good things start<br/>with <span className="orange-text">a little play.</span></h2><p>Find their next basketball adventure.</p></div><div className="camp-note"><CircleCheck size={19}/><span>Come as you are.<br/>Grow as you play.</span></div></div><Camps/></section>
   <section className="closing section-wrap"><span className="closing-star" aria-hidden="true">✳</span><div><p className="section-kicker">A LITTLE BASKETBALL. A WORLD OF POSSIBILITY.</p><h2>Let’s get them moving.</h2></div><a href="#camps" className="button button-light">Explore our camps <ArrowRight size={20}/></a></section>
  </main>
  <footer className="footer"><a href="#" className="brand"><span className="brand-mark">E</span><span>ELEVATE<small>SPORTS</small></span></a><p>Positive movement. Lasting impact.</p><span>© {new Date().getFullYear()} Elevate Sports</span></footer>
 </>;
}
